Repository Matt-Roden/pokedex, pull requests merged in 2021-09, with the labels that each got.

#10 Feature/readme
  README.md
Labels: documentation

#13 Feature/file structure
  cypress.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App.test.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/Error/Error.css
  src/components/Error/Error.js
  src/components/Help/Help.css
  src/components/Help/Help.js
  src/components/Loader/Loader.css
  src/components/Loader/Loader.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokedexGrid/PokedexGrid.js
  src/components/PokemonDetails/PokemonDetails.css
  src/components/PokemonDetails/PokemonDetails.js
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
  src/setupTests.js
Labels: documentation

#14 Feature/search
  package-lock.json
  src/components/App/App.js
  src/components/Search/Search.js
Labels: enhancement

#15 Feature/search data integration
  src/components/App/App.js
  src/components/Search/Search.js
Labels: enhancement

#18 Feature/pokedex grid
  src/components/App/App.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokedexGrid/PokedexGrid.js
  src/components/PokemonCard/PokemonCard.css
  src/components/PokemonCard/PokemonCard.js
Labels: enhancement, MVP

#21 Feature/start cypress test
  cypress/fixtures/example.json
  cypress/integration/home_page_spec.js
  cypress/integration/pokemon_info_spec.js
  cypress/support/commands.js
  package.json
Labels: enhancement, MVP

#23 Feature/main page styling i
  public/Images/ash1.png
  src/components/App/App.css
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/Search/Search.css
  src/components/Search/Search.js
  src/fonts.css
  src/fonts/PocketMonk-15ze.ttf
  src/index.css
Labels: enhancement

#24 Feature/pokemon detail
  src/components/App/App.js
  src/components/PokedexGrid/PokedexGrid.js
  src/components/PokemonCard/PokemonCard.js
  src/components/PokemonDetails/PokemonDetails.css
  src/components/PokemonDetails/PokemonDetails.js
Labels: bug, help wanted, MVP, Unfinished

#25 Feature/main page styling ii
  src/components/App/App.css
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokemonCard/PokemonCard.css
  src/components/PokemonCard/PokemonCard.js
  src/components/Search/Search.css
Labels: enhancement, MVP

#26 Feature/help
  src/components/Help/Help.css
  src/components/Help/Help.js
Labels: documentation, enhancement

#27 Feature/router
  package-lock.json
  package.json
  src/assets/x-icon.png
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Help/Help.css
  src/components/Help/Help.js
  src/components/Search/Search.js
  src/index.js
Labels: enhancement

#28 Fix/search bug
  src/components/App/App.js
  src/components/PokemonDetails/PokemonDetails.js
  src/components/Search/Search.js
Labels: fix

#35 Feature/icons
  public/Images/x-icon.png
  public/favicon.ico
  src/components/Help/Help.css
  src/components/Help/Help.js
  src/components/PokemonDetails/PokemonDetails.css
Labels: enhancement

#36 Feature/add pwa needed files
  src/index.js
  src/service-worker.js
  src/serviceWorkerRegistration.js
Labels: enhancement

#37 Bug fix/accessibility
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/Help/Help.css
  src/components/Help/Help.js
  src/components/PokemonDetails/PokemonDetails.css
  src/components/PokemonDetails/PokemonDetails.js
Labels: bug, enhancement

#38 Filter moves for gen 1
  src/components/PokemonDetails/PokemonDetails.js
Labels: bug, enhancement

#39 Feature/fix error message bug
  cypress/support/commands.js
  src/components/App/App.js
  src/components/Search/Search.js
Labels: fix

#40 Feature/mobile layout
  src/components/Header/Header.css
  src/components/PokedexGrid/PokedexGrid.css
Labels: enhancement, fix

#43 Bug fix/app
  public/manifest.json
  src/components/App/App.css
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/Help/Help.js
Labels: fix

#44 Feature/polishing css search
  src/components/App/App.css
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/HowTo/HowTo.css
  src/components/HowTo/HowTo.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokemonCard/PokemonCard.css
  src/components/PokemonDetails/PokemonDetails.css
  src/components/Search/Search.css
Labels: enhancement, fix

#45 Feature/refactor to hooks i
  package-lock.json
  src/components/App/App.js
  src/components/Search/Search.js
Labels: bug, enhancement, help wanted

#47 Fix/validation condition bug
  src/components/App/App.js
  src/components/PokemonDetails/PokemonDetails.js
  src/components/Search/Search.js
Labels: fix

#46 Features/css details
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/HowTo/HowTo.css
  src/components/HowTo/HowTo.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokemonDetails/PokemonDetails.css
  src/components/PokemonDetails/PokemonDetails.js
  src/components/Search/Search.css
Labels: fix

#48 Feature/sw caching
  public/offline.html
  public/serviceworker.js
  src/components/Header/Header.js
  src/index.js
Labels: enhancement

#50 Feature/layout details
  src/components/App/App.js
  src/components/Header/Header.js
  src/components/HowTo/HowTo.css
  src/components/HowTo/HowTo.js
  src/components/PokemonDetails/PokemonDetails.css
Labels: enhancement, fix

#54 Get HowTo button to hide
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/HowTo/HowTo.js
Labels: enhancement

#53 Feature/gsap jo v2
  src/components/App/App.js
  src/components/Header/Header.css
  src/components/Header/Header.js
  src/components/PokemonDetails/PokemonDetails.css
  src/components/PokemonDetails/PokemonDetails.js
Labels: enhancement, help wanted, Unfinished

#52 Fix merge bug
  src/components/App/App.js
Labels: fix

#56 Feature/howto final draft
  src/components/HowTo/HowTo.js
Labels: documentation

#58 Feature/cypress adjustment home page
  cypress/integration/home_page_spec.js
  cypress/integration/how_to_spec.js
  src/components/Header/Header.css
  src/components/Header/Header.js
Labels: Cypress Test, fix

#57 Fix/details page tests
  cypress/integration/pokemon_details_spec.js
  public/manifest.json
  src/components/App/App.js
  src/components/PokedexGrid/PokedexGrid.css
  src/components/PokemonCard/PokemonCard.css
Labels: fix

#59 Feature/details loader
  src/components/PokemonCard/PokemonCard.css
  src/components/PokemonDetails/PokemonDetails.js
Labels: fix

#61 Feature/screenshots
  README.md
  public/Images/desktop-home.png
  public/Images/desktop-pokemon.png
  public/Images/error.png
  public/Images/loader.png
  public/Images/mobile-home.png
  public/Images/mobile-pokemon.png
Labels: documentation, enhancement
